FROM        docker.dev.dszn.cz/doporucovani/dev/debian-python3:stretch

MAINTAINER  doporucovani-vyvoj "doporucovani-vyvoj@firma.seznam.cz"

LABEL       description="recass-jobslib"

COPY        . /www/recass/jobslib

WORKDIR     /www/recass/jobslib

RUN         apt-get update \
         && python3 setup.py develop